### ISSUE TITLE
[pixel4] Cannot load Android system. Your data may be corrupt

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#577]
# issue

Android phone only showed and not operatable normally. Screen reads as following, same as https://support.google.com/pixelphone/thread/17930356/is-there-a-way-to-bypass-the-cannot-load-android-system-error-without-losing-personal-data?hl=en:

> Cannot load Android system. Your data may be corrupt. If you continue to get this message, you may need to perform a factory data reset and erase all user data stored on this device

![IMG_20210902_041615](https://user-images.githubusercontent.com/1840401/131813094-79ec8e1a-0224-40f8-a582-96420a8de23d.jpg)

## What happened before seeing the issue
In the morning after it's fully charged, I unplugged, did some normal daily browsing, then put it in my pocket. A few minutes after that I saw this. Note I did NOT trigger a reboot/shutdown.

# Workaround worked
Press "Try again" rebooted Android and it seems to have rebooted normally.

# Additional info
- Replaced battery and frontpanel 5 days before #557. I have yet to reported how it's been though, there are a new behavior, which seems minor for now, that I had never seen.

**Comment by 130s** [comment]
Not seen again so far.

**Comment by PushoN** [comment]
i got the f** same issue, wtf google

<img width="1920" height="2560" alt="Image" src="https://github.com/user-attachments/assets/b36a4d5b-b8a3-4b53-b188-d8f746d707e5" />
